credentials:
  usernames:
    admin:
      name: 管理員
      password: $2b$12$67x.wXgUDL7cHf0E4nQI6eaPkBJprfQ5y.gU4qha7tfNnHkPYqMZe

cookie:
  name: ai_invest_hq
  key: 0b068d03b2ee077b2ccfebf63e6c82abe5f0b242c60cfbde0d01bb43326f5cbb
  expiry_days: 7
