credentials:
  usernames:
    admin:
      name: IsaacHuang
      password: $2b$12$hpkQdHZBjaH9cdEewmyN9O5GbfpXQTJhq7SQwCkZFCAKefSGY6Q6.
    Po:
      name: Po
      password: $2b$12$FR31pGEJwPiIZte1HP3gcebhBjk0CZnrPACYvSwC3IRLMkZ1AguNe
    Will:
      name: Will
      password: $2b$12$MkJrb8WUO1DDL8UvbuOG3.5kylZZjKiMX8fqadkAE4AAQxH1eaKR.

cookie:
  name: ai_invest_hq
  key: 0b068d03b2ee077b2ccfebf63e6c82abe5f0b242c60cfbde0d01bb43326f5cbb
  expiry_days: 7
